apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: cicd-demo-container
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"