resources:
- ../base
nameSuffix: -prod
patches:
- path: overlay.yaml
  target:
    kind: Deployment
    labelSelector: app=cicd-demo
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: minghsu0107/cicd-demo
  newTag: 0ca8d43aa9e4083ba756088d9d6ff21090555776
